### ISSUE TITLE
Feature Request: Block Access to Hidden Menu items

### ISSUE THREAD

**Issue by Malonsow** [GetSimpleCMS-CE-plugins/plugin-Massive_Admin_Theme#10]
Hi creators of MassiveAdminTheme,

I am passionate user of your work and would like to hand in a feature request.

When hiding admin menu bar options for some users, the menu options won't show up in UI but if user knows the URL to open they will still be able to see and change everything related.

For instance I have a user that is only allowed to see `Pages`. Admin UI only shows `Pages` tab accordingly. Still, if he opens `https://<GetSimpleBaseUrl>/admin/backups.php` he will be able to see and change the settings.

Am using MassiveAdminTheme in version 5.0.9 and was affected by this issue.

For me I circumvented it by placing following custom code in all `.php` files under `/admin` folder:

```php
global $USR;
if ($USR != '<yourAdminUser>') {
	die('Access Denied');
}
```

This way other users than admin will not be able to access unwanted pages at all.

Would be cool if similar logic could come with the theme directly. If I have some time I could start on this topic myself and suggest PR but can't promise when this will be.

**Comment by GetSimpleCMS-CE** [comment]
Thanks for your suggestion. Will try to get this into the next release.

**Comment by risingisland** [comment]
This has now been added in 5.0.10
